version: '3'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: breweries_dw
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  airflow:
    image: apache/airflow:2.7.1-python3.9
    container_name: airflow
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/breweries_dw
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'true'
      _AIRFLOW_WWW_USER_USERNAME: airflow
      _AIRFLOW_WWW_USER_PASSWORD: airflow
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      # Diretórios do seu repositório montados dentro do container
      - ./air_flow/dags:/opt/airflow/dags
      - ./air_flow/src:/opt/airflow/src
      # Para persistência dos dados do Airflow (opcional, mas recomendado)
      - airflow_logs:/opt/airflow/logs
      - airflow_tmp:/opt/airflow/tmp
    # user: "50000:0" # Use se precisar ajustar permissões

volumes:
  airflow_logs:
  airflow_tmp:
